language: ruby
sudo: false
before_install: >-
  if ruby -v | grep 'ruby 2.0';then
    gem install bundler -v '~> 1.3'
  elif ruby -v | grep 'ruby 2.4';then
    gem install bundler -v '~> 1.17'
  fi
rvm:
  - 2.0.0
  - 2.3.3
  - 2.4.5
  - 2.5.3
  - 2.6.5
script:
  - bundle exec rake
