language: ruby
sudo: false
before_install: >-
  if ruby -v | grep 'ruby 2.2'; then
    gem install bundler -v '~> 1.17'
  fi
rvm:
  - 2.2.10
  - 2.3.3
  - 2.5.3
  - 2.6.0
script:
  - bundle exec rake
